### ISSUE TITLE
Create event set time and date issues

### ISSUE THREAD

**Issue by joebeernink** [TrashMob-eco/TrashMob#1036]
When creating a new event, some actions around the time and date of the event will cause the date to jump back to the current date, or the time to jump back to midnight. This is a big issue because if the user saves the event with the wrong date, the email notifying all users of the event will be wrong, and the user won't get notified that the date or time has changed unless they register for the event. Fix the date changing behavior, then also fix it so that people not signed up for the event get notifications for it as well

**Comment by Limarulanda** [comment]
Looks like the Events request is being submitted with the incorrect date/time info as well:
![image](https://user-images.githubusercontent.com/97642703/224460600-f2725857-d876-4c70-bd3e-46698086e613.png)
