### ISSUE TITLE
Web- Fix event details mobile view 

### ISSUE THREAD

**Issue by Limarulanda** [TrashMob-eco/TrashMob#1067]
![image](https://user-images.githubusercontent.com/97642703/231901405-61930890-4c79-4fd1-9923-596f9634e6b2.png)

* Mobile view of website for event details needs to be fixed

**Comment by Limarulanda** [comment]
![image](https://user-images.githubusercontent.com/97642703/231902517-34894dd6-943c-42d6-9a40-5b8c278e3efd.png)
Event details

**Comment by XiaoStevens** [comment]
Design completed: Please check [prototype ](https://www.figma.com/proto/iiFi1rWzSgGBxbfarC5Bc9/TrashMob.Eco-Web?type=design&node-id=1595-2013&t=kB7OJwOnFOIEFknv-1&scaling=min-zoom&page-id=298%3A72&starting-point-node-id=1116%3A2301&mode=design)and [design file](https://www.figma.com/file/iiFi1rWzSgGBxbfarC5Bc9/TrashMob.Eco-Web?type=design&node-id=1595%3A2013&mode=design&t=lrZVYyRc2lRbxl1O-1)
