### ISSUE TITLE
Add search features for events

### ISSUE THREAD

**Issue by chunlishao** [TrashMob-eco/TrashMob#1157]
Chunli:
The events page can provide search features in the future, especially when more users join and more events are created.  Ex, event type, time, and location. It can help users filter information and make decisions easier. 

Joe:
Yes, Search is something we have talked about for a long time. Take a shot at it, and see what works! I think City, State, Country are probably the basics... though we also have a "Near me" feature in place that uses the user's location and their Preferred travel distance to find events close to them. This is used when we send out notifications of events so they only see ones in their area. We could have a "Show near me" button on the UI as well.

**Comment by chunlishao** [comment]
From Joe: With pagination also comes a need to be able to sort the results. Default sort should be by event date, descending. other options may be city, created by, created date, and event type

**Comment by XiaoStevens** [comment]
![image](https://github.com/TrashMob-eco/TrashMob/assets/52208750/8d988428-3b8f-42c5-a404-3e3f96eecce9)
Added "Distance near me" And "Sort by: Date/Distance" Here's [Figma prototype](https://www.figma.com/proto/iiFi1rWzSgGBxbfarC5Bc9/TrashMob.Eco-Web?type=design&node-id=1513-23982&t=Fsa8wQykrpKVMcyp-1&scaling=min-zoom&page-id=1254%3A20669&starting-point-node-id=1307%3A8681&show-proto-sidebar=1&mode=design) for play:   Here's[ Figma File](https://www.figma.com/file/iiFi1rWzSgGBxbfarC5Bc9/TrashMob.Eco-Web?type=design&node-id=1513%3A23982&mode=design&t=1qG5kgAnjM0edoSM-1) for develop:

**Comment by chunlishao** [comment]
https://github.com/TrashMob-eco/TrashMob/assets/116043159/c0a953bb-f764-4e88-952d-722947123080
