### ISSUE TITLE
HeroSection: The earth image is flat(-ten) on some screen sizes.

### ISSUE THREAD

**Issue by pitipatdop** [TrashMob-eco/TrashMob#1631]
### Expected: 
Earth Image maintain its original aspect ratio

### Actual: 
The image appears distorted, with the width and height not proportionally scaled

------
#### Width: 360px
<img width="362" alt="image" src="https://github.com/user-attachments/assets/31692f6a-fff3-4ca0-aaa7-281f1c75b4c2">

#### Width: 520px
<img width="521" alt="image" src="https://github.com/user-attachments/assets/d927e640-6516-4559-91d6-56fce5f44cef">

#### Width: 850px
<img width="851" alt="image" src="https://github.com/user-attachments/assets/711491a9-a3dd-43a5-bb57-b5c25e8b386e">

**Comment by Cililocwee** [comment]
This is addressed in the responsiveness ticket, but good catch. Once my PR is merged, this issue will be fixed.
