### ISSUE TITLE
Add Share Event Functionality to My Dashboard

### ISSUE THREAD

**Issue by joebeernink** [TrashMob-eco/TrashMob#596]
In the actions for each upcoming event, allow the user to share a link... see the event details page for what the share functionality currently does.

**Comment by chunlishao** [comment]
@joebeernink , I noticed that "Share" button available on eventdetails page for both upcoming and completed events. However, it shows "upcoming event" when sharing as below. 
![image](https://github.com/TrashMob-eco/TrashMob/assets/116043159/9c1ce06b-1f2c-42aa-af59-92f7d46023cd)
 
I think the "Share" function should have same availbility on mydashboard and eventdetails page, and 2 ways to implement:

1. Available for upcoming and completed events both. In this case, people can share their accomplishment after attended or organized an event. We need one picture for completed event to share.
2. Available for upcoming events only. The "Share" button needs to be disabled in eventdetails page for completed events.

 Which way you perfer?

**Comment by chunlishao** [comment]
issue fixed with pull request #1138
