### ISSUE TITLE
Unable to Delete event on Site Admin Page

### ISSUE THREAD

**Issue by joebeernink** [TrashMob-eco/TrashMob#929]
Tried deleting event on site admin. Command returns with 200... but never actually deletes.

**Comment by Limarulanda** [comment]
The event looks to actually delete from the dashboard and events page after deleting it on site admin, but it still shows up in the site admin page under "Manage Events" - would we want it to delete entirely from the site admin page as well?

**Comment by Limarulanda** [comment]
> The event looks to actually delete from the dashboard and events page after deleting it on site admin, but it still shows up in the site admin page under "Manage Events" - would we want it to delete entirely from the site admin page as well?
thank you!!
@joebeernink

**Comment by joebeernink** [comment]
Yes. When the record is deleted the view should refresh and show it deleted (canceled). We may want to add the status to the page.
